language: python
python:
- '2.7'
notifications:
  email: false
  slack:
    secure: lWJsUXTtmQJarJdLBlBXJCkbS4ttYDaIFYtcisv81PZwkrOX2WAOzYsVYqN3T6496ANbVtFBiUHFcp6dyKMIp/GjUkrYGkTzNCmnEcJcj6fuFdDb2NvvEI4rt+qa56bwF1TquVP5BXzEnCrDFcRMqbs8TJWKtfbzWgiqVUtZbD0=
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.8
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
- export CC=gcc-4.8
- export CXX=g++-4.8
- wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
- conda install --yes conda-server conda-build jinja2 anaconda-client sh
- conda config --add channels distributions
- conda config --add channels datamicroscopes
- git config --global user.email "datamicroscopes.travis.builder@gmail.com"
- git config --global user.name "datamicroscopes-travis-builder"
- git config --global push.default simple
env:
  global:
  - secure: m2LUlcPzgxsE9Ta1zlGqUCqanfn2JEgF4TKF/MeGPBQCtwneu1aq0tqNpSEr6FBNUCbqo5hWcOz5+T6L7uDuv+w59yA0shcY0xwrMBsptNhWfjCXtsiyQ8DhpJSbsdESj3brh+Je0cuJqsGXzrpFznI2L+qouTy+DLBp+baHcfM=
  - secure: Na4iSuixnYsqr0HDnVmkjly/AyTewEUkUwRot+R9nN7m4vB0x4TqtjPKUSx5771zftrIYqIZY3HXmOvM3DvYc+LmykZIEuE0Ci/kVpn3YIOyA/bFRjeOPQHXao6408jprD30PJCR0y/W5s78OTqBBNpr6kWc76clGxBvdPJu+dI=
install:
- echo "nothing to do"
script:
- python build.py --project common
- python build.py --project mixturemodel
- python build.py --project irm
- python build.py --project kernels
after_success:
- conda install --yes microscopes-common microscopes-mixturemodel microscopes-irm
  microscopes-kernels
- conda install --yes sphinx pip
- which pip
- pip install numpydoc
- git clone "https://datamicroscopes-travis-builder:$GITHUB_PASSWORD@github.com/datamicroscopes/datamicroscopes.github.io"
  D
- "(cd doc && make html)"
- rm -rf D/*
- cp -R doc/_build/html/* D
- "(cd D && git add *)"
- (cd D && git commit -m "autogen docs")
- "(cd D && git push -q)"
