language: python
os:
  - linux
python:
- '2.7'
notifications:
  email: false
  slack:
    secure: lWJsUXTtmQJarJdLBlBXJCkbS4ttYDaIFYtcisv81PZwkrOX2WAOzYsVYqN3T6496ANbVtFBiUHFcp6dyKMIp/GjUkrYGkTzNCmnEcJcj6fuFdDb2NvvEI4rt+qa56bwF1TquVP5BXzEnCrDFcRMqbs8TJWKtfbzWgiqVUtZbD0=
before_install:
- [ "${TRAVIS_OS_NAME}" == "linux" ] && . ./linux_prebuild.sh
- printenv
env:
  global:
  - secure: m2LUlcPzgxsE9Ta1zlGqUCqanfn2JEgF4TKF/MeGPBQCtwneu1aq0tqNpSEr6FBNUCbqo5hWcOz5+T6L7uDuv+w59yA0shcY0xwrMBsptNhWfjCXtsiyQ8DhpJSbsdESj3brh+Je0cuJqsGXzrpFznI2L+qouTy+DLBp+baHcfM=
  - secure: Na4iSuixnYsqr0HDnVmkjly/AyTewEUkUwRot+R9nN7m4vB0x4TqtjPKUSx5771zftrIYqIZY3HXmOvM3DvYc+LmykZIEuE0Ci/kVpn3YIOyA/bFRjeOPQHXao6408jprD30PJCR0y/W5s78OTqBBNpr6kWc76clGxBvdPJu+dI=
install:
- echo "nothing to do"
script:
- python build.py --project common
- python build.py --project mixturemodel
- python build.py --project irm
- python build.py --project kernels
- python build.py --project lda
after_success:
- conda install --yes microscopes-common microscopes-mixturemodel microscopes-irm microscopes-lda
  microscopes-kernels
- conda install --yes sphinx pip
- which pip
- pip install numpydoc
- git clone "https://datamicroscopes-travis-builder:$GITHUB_PASSWORD@github.com/datamicroscopes/datamicroscopes.github.io"
  D
- "(cd doc && make html)"
- rm -rf D/*
- cp -R doc/_build/html/* D
- "(cd D && git add *)"
- (cd D && git commit -m "autogen docs")
- "(cd D && git push -q)"
